### ISSUE TITLE
int and bool are syntax highlighted when substrings of identifiers

### ISSUE THREAD

**Issue by knarfchan** [Chillee/VSCode-Xi#2]
Keywords int and bool are syntax highlighted when substrings of identifiers for interfaces, variables, and arguments. They can be substrings of function names without syntax highlighting however.

For example
<img width="217" alt="screen shot 2018-04-30 at 10 50 17 pm" src="https://user-images.githubusercontent.com/8468598/39459363-e8925602-4cc8-11e8-9850-c405af22c103.png">

**Comment by Chillee** [comment]
Fixed in newest commit: https://github.com/Chillee/VSCode-Xi/commit/e5e833546b4866ee84514c26e7597e5d10560031
